version: '3.8'

services:
  # Emulador oficial de AWS DynamoDB
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dbae-dynamodb-local
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    restart: unless-stopped

  # LocalStack configurado únicamente para SQS
  localstack:
    image: localstack/localstack:3.8.0
    container_name: dbae-localstack-sqs
    ports:
      - "4566:4566" # Puerto unificado de LocalStack
    environment:
      - SERVICES=sqs # Restringimos el alcance solo a SQS
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack
      - ./scripts:/etc/localstack/init/ready.d
    restart: unless-stopped

volumes:
  dynamodb_data:
    driver: local
  localstack_data:
    driver: local
